### ISSUE TITLE
missing support for decoding `.zst` compressed repository metadata

### ISSUE THREAD

**Issue by dirkmueller** [ikapelyukhin/repomd-parser#12]
There's handling for gzip here:

https://github.com/ikapelyukhin/repomd-parser/blob/ec7ffdcc50458f9825f456c5f026079e0da27dfb/lib/repomd_parser/base_parser.rb#L29C1-L32

however no corresponding handling for `.zst` (ZSTD) compression. ZSTD is the default compression type created by createrepo_c >= 1.0.0 and many distributions (Fedora, openSUSE) are switching to it because of the higher compression ratios and much higher decompression speed.

**Comment by ikapelyukhin** [comment]
@dirkmueller Hi, Dirk. If you could please provide me with a URL of a repo that already has ZSTD enabled, I can look into adding support for ZSTD.

**Comment by dirkmueller** [comment]
Sure  for example https://download.opensuse.org/tumbleweed/repo/non-oss/

**Comment by ikapelyukhin** [comment]
Implemented in #13. Released in v0.1.6.
